services:
  server:
    build:
      context: apps/server
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NATS_URLS=nats://nats:4222
      - MONGODB_URI_DEV=mongodb://mongodb:27017/lms
      - REDIS_URL_DEV=redis://redis:6379
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    command: ["pnpm", "start"]
    depends_on:
      - mongodb
      - nats
      - redis
    
  client:
    build:
      context: apps/client
      dockerfile: DockerFile
    ports:
      - "3001:3000"
    environment:
      - NATS_URLS=nats://nats:4222
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    command: ["pnpm", "dev"]
    depends_on:
      - nats

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--http_port", "8222"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongodb/mongodb-community-server:8.0.9-ubuntu2204
    command: ['--replSet', 'rs1', '--bind_ip_all', '--port', '27017']
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({ _id: 'rs1', members: [{ _id: 0, host: 'mongodb' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      start_period: 5s


volumes:
  dbdata:
  redisdata:
