import type { Metadata } from "next";
// import { redirect } from 'next/navigation';
// import { routing } from '@/i18n/routing';


// import { Geist, Geist_Mono } from "next/font/google";
// import "./../globals.css";
// import { getMessages, setRequestLocale } from "next-intl/server";
import NavBar from "./__sections/nav-bar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};




export default async function LocaleLayout({
    children,
    params
}: LayoutProps<'/[locale]'>) {



    //   const messages = await getMessages(); // will load messages for current locale


    return (
        <>
            <NavBar />
            {children}
        </>

    );
}
