From node:22

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml files
COPY package.json  ./
# Install pnpm globally
RUN npm install -g pnpm
# Install dependencies
RUN pnpm install 
# Copy the rest of the application code
# COPY . .
# # Build the application
# RUN pnpm build