import type { Metadata } from "next";
import { redirect } from 'next/navigation';
import { routing } from '@/i18n/routing';


import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import { setRequestLocale } from "next-intl/server";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function LocaleLayout({
  children,
  params
}: LayoutProps<'/[locale]'>) {

  const { locale } = await params;

  if (!routing.locales.includes(locale as "en" | "ar")) {
    redirect("/ar/" + locale)
  }



  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`} >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
