import type { Metadata } from 'next';
import Footer from '@/components/organs/footer';
import HomeNave from '@/components/organs/home-nav';
import { getAuthUser } from '@/lib/actions/user/user.action';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<'/[locale]'>) {
  const user = await getAuthUser();

  return (
    <>
      <HomeNave user={user} />
      {children}
      <Footer />
    </>

  );
}
