import { Navbar02 } from "@/components/molecules/nav-bar";
import HomeNave from "@/components/organs/home-nav";
import { getAuthUser } from "@/lib/actions/user/user.action";
import type { Metadata } from "next";

// import { redirect } from 'next/navigation';
// import { routing } from '@/i18n/routing';


// import { Geist, Geist_Mono } from "next/font/google";
// import "./../globals.css";
// import { getMessages, setRequestLocale } from "next-intl/server";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};




export default async function LocaleLayout({
    children,
    params
}: LayoutProps<'/[locale]'>) {
    return (
        <>
            {children}
        </>

    );
}
